### Get All Books
@bookId = a1b2c3d4-e5f6-7890-abcd-ef1234567890
GET http://localhost:3000/books

### Get One Book by ID
GET http://localhost:3000/books/{{bookId}}

### Create Book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "The Pragmatic Programmer",
  "author": "Andrew Hunt & David Thomas",
  "publishedYear": 1999,
  "publisherId" : "903b4d2a-59e4-4a01-bdba-6d368877044"
}

### Update Book
PATCH http://localhost:3000/books/{{bookId}}
Content-Type: application/json

{
  "title": "The Pragmatic Programmer",
  "author": "Andrew Hunt & David Thomas",
  "publishedYear": 1999,
  "publisherId" : "903b4d2a-59e4-4a01-bdba-6d368877044"
}


### Delete Book
DELETE http://localhost:3000/books/{{bookId}}