### Get All Books
@bookId = a1b2c3d4-e5f6-7890-abcd-ef1234567890
GET http://localhost:3000/books

### Get One Book by ID
GET http://localhost:3000/books/{{bookId}}

### Create Book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "The Pragmatic Programmer",
  "author": "Andrew Hunt & David Thomas",
  "publishedYear": 1999
}

### Update Book
PATCH http://localhost:3000/books/{{bookId}}
Content-Type: application/json

{
  "title": "The Pragmatic Programmer",
  "author": "Andrew Hunt & David Thomas",
  "publishedYear": 1999
}


### Delete Book
DELETE http://localhost:3000/books/{{bookId}}