@url = http://localhost:3030/inventory

PATCH {{url}}/i-a2/add
Content-Type: application/json

{
  "quantity" : 7,
  "name" : "Tea"
}

###

PATCH {{url}}/i-a2/withdraw
Content-Type: application/json

{
  "quantity" : 0,
  "name" : "Tea"
}