@url = http://localhost:3030/tasks

# @name createTask
POST {{url}}
Content-Type: application/json

{
  "title" : "Reading a book",
  "priority" : " lOw ",
  "status" : "completed"
}
###

DELETE {{url}}/{{createTask.response.body.result.id}}
x-roles: "admin"
